### PR TITLE
fixed docker hub URL

### PR DESCRIPTION
**Pull request by tronicum**

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
Can you please update the Author field for your patch to include your full real name?

**Comment by tronicum** [comment]
> Can you please update the Author field for your patch to include your full real name?
> 
> May I ask why?  Even docker accepts commits with my handle and I do not see a requirement or reason to do so. 

The fix is even so small that you could not  claim a copyright on it. 

I make all my Wikipedia edits likewise, properly licensed as Creative Commons. 

Regards, 
  Tronicum

**Comment by gunnarbeutner** [comment]
Oh, sorry, I thought this was for the 'icinga2' repository. Nevermind then. :)

**Comment by dnsmichi** [comment]
Merged, thanks 👍

**Pull request closed without merging**
